export enum ElementType {
    Button = "LiteRenderer_Button",
    Label = "LiteRenderer_Label",
    Chip = "LiteRenderer_Chip",
    TextInput = "LiteRenderer_TextInput",
    Image = "LiteRenderer_Image",
    Container = "LiteRenderer_Container",
    Tab = "LiteRenderer_Tab",
    Grid = "LiteRenderer_Grid",
    Modal = "LiteRenderer_Modal",
    SELECT_BOX = "LITE_RENDERER_SELECT_BOX",
    SELECT_BOX_GROUP = "LITE_RENDERER_SELECT_BOX_GROUP",
    DATE_PICKER = "LITE_RENDERER_DATE_PICKER",
    TIME_PICKER = "LITE_RENDERER_TIME_PICKER",
}
