export enum ElementType {
    Button = "LiteRenderer_Button",
    Label = "LiteRenderer_Label",
    Chip = "LiteRenderer_Chip",
    TextInput = "LiteRenderer_TextInput",
    Image = "LiteRenderer_Image",
    Container = "LiteRenderer_Container",
    TAB = "LITE_RENDERER_TAB",
    GRID = "LITE_RENDERER_GRID",
    MODAL = "LITE_RENDERER_MODAL",
    SELECT_BOX = "LITE_RENDERER_SELECT_BOX",
    SELECT_BOX_GROUP = "LITE_RENDERER_SELECT_BOX_GROUP",
    DATE_PICKER = "LITE_RENDERER_DATE_PICKER",
    TIME_PICKER = "LITE_RENDERER_TIME_PICKER",
}
